/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.banhangBLL;
import BLL.thietbiBLL;
import DTO.thietbiDTO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nngia
 */
public class BanhangGUI extends javax.swing.JPanel {
    banhangBLL bll = new banhangBLL();
    thietbiBLL tbbll = new thietbiBLL();
    float tongtien=0;
     JTextArea hd = new JTextArea();
    /**
     * Creates new form BanhangGUI
     */
    public BanhangGUI() {
        initComponents();
        loadDssp(new thietbiBLL().docThietbi());
        loadBaogiatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        dssptable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        baogiatable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        giatxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        thanhtoanbtn = new javax.swing.JButton();
        inbtn = new javax.swing.JButton();
        xoabtn = new javax.swing.JButton();

        dssptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dssptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dssptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dssptable);

        baogiatable.setModel(new javax.swing.table.DefaultTableModel(
            null,new String [] {
                "ID","Tên sản phẩm","Đơn giá", "Số lượng","Thành tiền"
            }
        ));
        baogiatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baogiatableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(baogiatable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BẢNG BÁO GIÁ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("DANH SÁCH SẢN PHẨM ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("TỔNG CỘNG:");

        giatxt.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        giatxt.setForeground(new java.awt.Color(255, 0, 0));
        giatxt.setText("0");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("QUẢN LÝ BÁN HÀNG");

        thanhtoanbtn.setText("Thanh toán");
        thanhtoanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhtoanbtnActionPerformed(evt);
            }
        });

        inbtn.setText("Xem lịch sử ");
        inbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbtnActionPerformed(evt);
            }
        });

        xoabtn.setText("Xóa");
        xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(xoabtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(thanhtoanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xoabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(giatxt)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thanhtoanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dssptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dssptableMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            boolean check = false;
            int i = dssptable.getSelectedRow();
            float temp;
            bll.themGiohang(dssptable.getValueAt(i,0).toString(),1,temp=Float.parseFloat(dssptable.getValueAt(i,4).toString()),temp);
            DefaultTableModel model = (DefaultTableModel) baogiatable.getModel();
            for(int j=0;j<baogiatable.getRowCount();j++){
                if(dssptable.getValueAt(i,0).toString().equals(baogiatable.getValueAt(j,0).toString())){
                    baogiatable.setValueAt(Integer.toString(Integer.parseInt(baogiatable.getValueAt(j,3).toString())+1),j,3);
                    baogiatable.setValueAt(Float.toString(Float.parseFloat(baogiatable.getValueAt(j,2).toString())*Integer.parseInt(baogiatable.getValueAt(j,3).toString())),j,4);
                    dssptable.setValueAt(Integer.toString((Integer.parseInt(dssptable.getValueAt(i,3).toString())-1)),i,3);
                    check = true;
                    break;
                }
            }
            if(check == false){
                dssptable.setValueAt(Integer.toString(Integer.parseInt(dssptable.getValueAt(i,3).toString())-1),i,3);
                Object [] newrow = {dssptable.getValueAt(i,0).toString(),dssptable.getValueAt(i,1).toString(),Float.toString(temp),1,Float.toString(temp)};
                model.addRow(newrow);
            }
            baogiatable.setModel(model);
            giatxt.setText(Float.toString(tongtien+=temp));
            JOptionPane.showMessageDialog(null,"Thành công");
        };
    }//GEN-LAST:event_dssptableMouseClicked

    private void thanhtoanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhtoanbtnActionPerformed
        // TODO add your handling code here:
        HoadonDialog a = new HoadonDialog(tongtien);
        a.setVisible(true);
        DefaultTableModel dtm = (DefaultTableModel) baogiatable.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_thanhtoanbtnActionPerformed

    private void xoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabtnActionPerformed
        // TODO add your handling code here:
        int i;String id="";
        if((i=baogiatable.getSelectedRow()) < 0){
            JOptionPane.showMessageDialog(null,"Chọn sản phẩm cần xóa");
        }else{
            for(int j=0;j<dssptable.getRowCount();j++){
                if((id=baogiatable.getValueAt(i,0).toString()).equals(dssptable.getValueAt(j,0).toString())){
                    tongtien-=Float.parseFloat(baogiatable.getValueAt(i,4).toString());
                    dssptable.setValueAt(Integer.toString(Integer.parseInt(dssptable.getValueAt(j,3).toString())+Integer.parseInt(baogiatable.getValueAt(i,3).toString())),j,3);
                    break;
                }
            }
            bll.xoaGiohang(id);
            giatxt.setText(Float.toString(tongtien));
            DefaultTableModel  model = (DefaultTableModel) baogiatable.getModel();
            model.removeRow(baogiatable.getSelectedRow());
        }
    }//GEN-LAST:event_xoabtnActionPerformed

    private void inbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbtnActionPerformed
        // TODO add your handling code here:
        hoadonGUI a = new hoadonGUI();
        a.setVisible(true);
        
    }//GEN-LAST:event_inbtnActionPerformed

    private void baogiatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baogiatableMouseClicked
        // TODO add your handling code here:
        if(baogiatable.getSelectedColumn() == 3 && evt.getClickCount()==2){
            int i = baogiatable.getSelectedRow(),input=0;
            String id;
            input = Integer.parseInt(JOptionPane.showInputDialog("Nhập số lượng cần thay đổi"));
            for(int j=0;j<dssptable.getRowCount();j++){
                if((id=baogiatable.getValueAt(i,0).toString()).equals(dssptable.getValueAt(j,0).toString())){
                    if(input > (Integer.parseInt(dssptable.getValueAt(i,3).toString())+Integer.parseInt(baogiatable.getValueAt(i,3).toString()))){
                        JOptionPane.showMessageDialog(null,"Số lượng tồn kho không đủ");
                    }else{
                        dssptable.setValueAt(Integer.toString(Integer.parseInt(dssptable.getValueAt(j,3).toString())+Integer.parseInt(baogiatable.getValueAt(i,3).toString())-input),j,3);
                        tongtien-= Float.parseFloat(baogiatable.getValueAt(i,4).toString());
                        baogiatable.setValueAt(input,i,3);
                        baogiatable.setValueAt(Float.toString(Float.parseFloat(baogiatable.getValueAt(i,2).toString())*Integer.parseInt(baogiatable.getValueAt(i,3).toString())),i,4);
                        tongtien+= Float.parseFloat(baogiatable.getValueAt(i,4).toString());
                        bll.suaSl(id,input);
                    }
                    break;
                }
            }
            giatxt.setText(Float.toString(tongtien));
        }
        
        if(baogiatable.getSelectedColumn() == 2 && evt.getClickCount()==2){
            int i = baogiatable.getSelectedRow(),input=0;
            String id=dssptable.getValueAt(i,0).toString();
            input = Integer.parseInt(JOptionPane.showInputDialog("Nhập số tiền cần thay đổi"));
            tongtien-= Float.parseFloat(baogiatable.getValueAt(i,4).toString());
            baogiatable.setValueAt(Float.toString(input),i,2);
            baogiatable.setValueAt(Float.toString(Float.parseFloat(baogiatable.getValueAt(i,2).toString())*Integer.parseInt(baogiatable.getValueAt(i,3).toString())),i,4);
            tongtien+= Float.parseFloat(baogiatable.getValueAt(i,4).toString());
            bll.suaDongia(id,input);
            giatxt.setText(Float.toString(tongtien));
        }
    }//GEN-LAST:event_baogiatableMouseClicked
    private void loadBaogiatable(){
        String[] header = {"ID","Tên sản phẩm","Đơn giá","Số lượng","Thành tiền"};
        DefaultTableModel model = new DefaultTableModel(header,0){
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        baogiatable.setSelectionMode(SINGLE_SELECTION);
        baogiatable.setModel(model);
    } 
    
    private void loadDssp(ArrayList<thietbiDTO> list){
        String[] header = {"ID","Tên sản phẩm","Mô tả","Tồn kho","Đơn giá"};
        DefaultTableModel model = new DefaultTableModel(header,0){
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        dssptable.setSelectionMode(SINGLE_SELECTION);
        dssptable.setModel(model);
        
        for(thietbiDTO sp : list){
            Object[] data = {sp.getSp_id(),sp.getSp_ten(),sp.getSp_mota(),sp.getSp_tonkho(),sp.getSp_dongia()};
            model.addRow(data);
        }
        
        dssptable.getColumnModel().getColumn(0).setPreferredWidth(1);
        dssptable.getColumnModel().getColumn(1).setPreferredWidth(70);
        dssptable.getColumnModel().getColumn(2).setPreferredWidth(150);
        dssptable.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
     public static void main(String[] args) {
        BanhangGUI b = new BanhangGUI();
         JFrame a = new JFrame();
         a.setSize(800,600);
         a.add(b);
        a.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable baogiatable;
    private javax.swing.JTable dssptable;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel giatxt;
    private javax.swing.JButton inbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton thanhtoanbtn;
    private javax.swing.JButton xoabtn;
    // End of variables declaration//GEN-END:variables
}
