/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.LeftMenu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Nam
 */
public class OverrallFrame extends javax.swing.JFrame implements MouseListener {
    int y = 0;
    Color hover = new Color(204,204,204);
    Color normal = new Color(255,255,255);
    Color clickPanel = new Color(0,51,255);
    Color clickText = new Color(255,255,255);
    Color releaseText = new Color(0,0,0);
    String arr[] = {"TRANG CHỦ", "QUẢN LÝ THIẾT BỊ","QUẢN LÝ PHIẾU NHẬP"
            ,"BÁN HÀNG","QUẢN LÝ HÀNH KHÁCH","THỐNG KÊ"};
    String arrIcon[] = {"icons8-home-page-20.png","icons8-collectibles-20.png",
        "icons8-management-20.png","icons8-address-20.png",
        "icons8-online-support-20.png","icons8-reception-20.png","icons8-increase-20.png"};
    private ArrayList<LeftMenu> navObj = new ArrayList<>();
    /**
     * Creates new form OverrallFrame
     */
    public OverrallFrame() {
        initComponents();
        leftmenu();
        changeMainInfo(1);
        navObj.get(0).doActive();
        setLocationRelativeTo(null);
    }
    
    private void leftmenu() {
        for(int i = 0; i< arr.length; i++)
        {  
            navObj.add(new LeftMenu(arr[i], new Dimension(210, 45), arrIcon[i]));
            navObj.get(i).addMouseListener(this);
            //duyet mang menu
            for (LeftMenu n : navObj) 
            {
                LeftPanel.add(n);//add vao thanh menu
            }
            LeftPanel.repaint();
            LeftPanel.revalidate();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1020, 670));
        jPanel2.setMinimumSize(new java.awt.Dimension(1020, 670));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 670));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeftPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        LeftPanel.setAlignmentX(0.0F);
        LeftPanel.setAlignmentY(0.0F);
        LeftPanel.setMaximumSize(new java.awt.Dimension(210, 580));
        LeftPanel.setMinimumSize(new java.awt.Dimension(210, 40));
        LeftPanel.setPreferredSize(new java.awt.Dimension(210, 580));
        LeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
        jPanel2.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 320));

        content.setBackground(new java.awt.Color(0, 0, 0));
        content.setMaximumSize(new java.awt.Dimension(800, 600));
        content.setMinimumSize(new java.awt.Dimension(800, 600));
        content.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel2.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 800, -1));

        headerPanel.setBackground(new java.awt.Color(102, 102, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 51, 255)));
        headerPanel.setMaximumSize(new java.awt.Dimension(1000, 70));
        headerPanel.setPreferredSize(new java.awt.Dimension(1000, 70));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PHẦN MỀM QUẢN LÝ BÁN HÀNG");
        headerPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 540, 70));

        jPanel2.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/SGUTemplateImage11.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverrallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverrallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverrallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverrallFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverrallFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftPanel;
    public static javax.swing.JPanel content;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        for(int i = 0; i< navObj.size(); i++)
            {
                LeftMenu item = navObj.get(i);
                if(e.getSource().equals(item))
                    {
                        item.doActive(); // Active NavItem đc chọn 
                        changeMainInfo(i+1);//truyền xuong de thay doi content
                    }
                else
                    {
                        item.noActive();
                    }
            }
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
    
    public static void changeMainInfo(int i)
    {
        JPanel p1;
        switch(i)
        {
            case 1: //  Trang chủ            
                content.removeAll();
                p1 = new TrangchuPanel();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 2: // Quản lý thiết bị
                content.removeAll();
                p1 = new QLthietbiGUI();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 3: // Quản lý pn
                content.removeAll();
                p1 = new QuanLyPhieuNhap();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 4: //bán h    
                content.removeAll();
                p1 = new BanhangGUI();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 5: //quản lý hành khách
                content.removeAll();
                p1 = new GuestMainPanel();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 6: //thống kê
                content.removeAll();
                p1 = new ThongkePanel();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 8: //thêm nhân viên
                content.removeAll();
                p1 = new AddThietbiPanel();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 9: //sửa nhân viên
                content.removeAll();
                p1 = new EditThietbiPanel();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 10: //thêm khách
                content.removeAll();
                p1 = new PhieuNhapGUI();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            /*case 11: //sửa khách
                content.removeAll();
                //p1 = new EditGuestPanel();
                p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 12: //thêm đoàn
                content.removeAll();
                //p1 = new AddDoanPanel();
               // p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 13: //sửa đoàn
                content.removeAll();
                //p1 = new EditDoanPanel();
              //  p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 14: //thêm chi phí
                content.removeAll();
               // p1 = new AddChiphiDoanPanel();
               // p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;
            case 15: //sửa chi phí
                content.removeAll();
               // p1 = new EditChiphiDoanPanel();
               // p1.setSize(800,600);
                content.add(p1);
                content.repaint();
                content.revalidate();
                break;       */    
        }
    }
}
