/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.table.DefaultTableModel;
import BLL.thietbiBus;
import DTO.thietbiDTO;
import java.awt.Image;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HOANG MINH HUY
 */
public class QLthietbiGUI extends javax.swing.JPanel {
    
 //   FormatTable formatTable = new FormatTable();
    thietbiBus tbBus = new thietbiBus();
    DefaultTableModel dtm=new DefaultTableModel();
    public static int currentIdTB;
    ImageIcon img;
    /**
     * Creates new form QLthietbiGUI
     */
    public QLthietbiGUI() {
        initComponents();
        init();
    }
    
    public void init(){
        tbBus.docThietbi();
        Vector header =new Vector();
        header.add("Id");
        header.add("Tên");
        header.add("Loại_id");
        header.add("Mô tả");
        header.add("Sản phẩm tồn kho");
        header.add("Sản phảm đã bán");
        header.add("Đơn gia");
        if(dtm.getRowCount()==0)
        {
            dtm= new DefaultTableModel(header, 0){
                @Override//no edit
                public boolean isCellEditable(int column, int row) {
                    if(column==6){
                    return true;
                }
                else{
                    return false;
                }
  //                  return super.isCellEditable(i, i1); //To change body of generated methods, choose Tools | Templates.
                }       
        };
        }
        table.setModel(dtm);
        docThietbiG();
    }
    public void refresh(){
        init();
        seachTxt.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void docThietbiG(){
        try {
            int rowCount = dtm.getRowCount();//remove all row
            for(int i=rowCount -1; i>0; i--){
                dtm.removeRow(i);
            }
            for(thietbiDTO a : thietbiBus.sumArrtb){
            Vector row = new Vector();
            row.add(a.getSp_id());
            row.add(a.getSp_ten());
            row.add(a.getLoai_id());
            row.add(a.getSp_mota());
            row.add(a.getSp_tonkho());
            row.add(a.getSp_daban());
            row.add(a.getSp_dongia());
//            row.add(a.getSp_img());
                dtm.addRow(row);
            }
            table.setModel(dtm);
            
        } catch (Exception e) {
            System.out.println("doc Thiet Bi that bai");
        }
    }
    public void search(){
        int countRow =dtm.getRowCount();
        for(int i=countRow-1; i>=0; i--){
            dtm.removeRow(i);
        }
        for(thietbiDTO a: tbBus.search(seachTxt.getText().toUpperCase(), combobox.getSelectedIndex())){
            Vector row=new Vector();
            row.add(a.getSp_id());
            row.add(a.getSp_ten());
            row.add(a.getLoai_id());
            row.add(a.getSp_mota());
            row.add(a.getSp_tonkho());
            row.add(a.getSp_daban());
            row.add(a.getSp_dongia());
//            row.add(a.getSp_img());
            dtm.addRow(row);
        }
        table.setModel(dtm);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combobox = new javax.swing.JComboBox<>();
        seachTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        nhaphangbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        combobox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Laptop", "Bàn Phím", "Màn Hình", "Chuột Gaming", "Tai Nghe" }));

        seachTxt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        seachTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachTxtActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-find-and-replace-20.png"))); // NOI18N
        searchBtn.setText("Tìm");
        searchBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchBtnItemStateChanged(evt);
            }
        });
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-available-updates-20.png"))); // NOI18N
        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        nhaphangbtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nhaphangbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-money-transfer-20.png"))); // NOI18N
        nhaphangbtn.setText("Nhập hàng");
        nhaphangbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaphangbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Loại Sản Phẩm");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/label.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jButton1.setText("Mở hình");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editBtn1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-edit-20.png"))); // NOI18N
        editBtn1.setText("Sửa thông tin");
        editBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(seachTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combobox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nhaphangbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nhaphangbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seachTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 790, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("DANH SÁCH THIẾT BỊ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 480, 60));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 830, 130));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 780, 250));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Quản Lý Thiết Bị");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 280, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchBtnItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchBtnItemStateChanged

    private void seachTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seachTxtActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void nhaphangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaphangbtnActionPerformed

        OverrallFrame.changeMainInfo(10);
    }//GEN-LAST:event_nhaphangbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(table.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn thiết bị");
        } else {
            int i = table.getSelectedRow();
            currentIdTB = Integer.parseInt(table.getValueAt(i, 0).toString());
//            OverrallFrame.changeMainInfo(9);
        }
        Image a = new ImageIcon(this.getClass().getResource("/IMG/"+currentIdTB+".jpg")).getImage().getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
            img = new ImageIcon(a);
            jLabel5.setIcon(img);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableMouseClicked

    private void editBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn1ActionPerformed
        // TODO add your handling code here:
        if(table.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn thiết bị cần sửa thông tin");
        } else {
            int i = table.getSelectedRow();
            EditThietbiPanel.currentIdTB = Integer.parseInt(table.getValueAt(i, 0).toString());
            OverrallFrame.changeMainInfo(9);
        }
    }//GEN-LAST:event_editBtn1ActionPerformed
public static void main(String[] args) 
    {
        JFrame j = new JFrame();
        j.setSize(1160,700);
        j.setLayout(null);
        JPanel p =new QLthietbiGUI();
        p.setBounds(0, 0, 1160, 700);
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nhaphangbtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField seachTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
