/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.thietbiBus;
import BLL.chitietphieunhapBUS;
import DTO.phieunhapDTO;
import BLL.phieunhapBUS;
import DTO.chitietphieunhapDTO;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY PC
 */
public class QuanLyPhieuNhap extends javax.swing.JPanel 
{
    DefaultTableModel model =new DefaultTableModel();
    DefaultTableModel modelTb2 =new DefaultTableModel();
    JLabel suaBtn;
    JTextFieldDateEditor txngnhap;
    public static String layidpn;
    thietbiBus nvbus = new thietbiBus();
//    layidpn=
    String ngnhap = "";
    
    String trangthai ="";
    SimpleDateFormat sp;
    /**
     * Creates new form phieunhapGUI
     */
    public QuanLyPhieuNhap() 
    {
        initComponents();
        inTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablephieunhap = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChitiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ChitietBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 650));
        setPreferredSize(new java.awt.Dimension(950, 650));

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));

        tablephieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablephieunhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablephieunhap.setRowHeight(20);
        tablephieunhap.setShowVerticalLines(false);
        tablephieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablephieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablephieunhap);

        tableChitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableChitiet);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Danh sách phiếu nhập");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Chi tiết phiếu nhập");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-level-up-30.png"))); // NOI18N
        jButton1.setText("In phiếu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(279, 279, 279)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(139, 139, 139))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-installing-updates-30.png"))); // NOI18N
        jLabel3.setText("Lịch sử nhập hàng");

        ChitietBtn.setBackground(new java.awt.Color(255, 153, 0));
        ChitietBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ChitietBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChitietBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChitietBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-clear-symbol-30.png"))); // NOI18N
        ChitietBtn.setText("Quay lại");
        ChitietBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChitietBtn.setOpaque(true);
        ChitietBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChitietBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChitietBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChitietBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(ChitietBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ChitietBtn))
                .addGap(18, 18, 18)
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void inTable()//doc du lieu in vao table
    {
        try
        {
        //render();
        phieunhapBUS bus = new phieunhapBUS();
        bus.docphieunhap();
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
        Vector header = new Vector();
        header.add("ID PN");
        header.add("Ngày nhập");
        if (model.getRowCount()==0)
            { 
                model=new DefaultTableModel(header,0);
            } 
        for(phieunhapDTO pn : phieunhapBUS.dspn)
        {
                Vector row = new Vector();
                row.add(pn.getPn_id());
                row.add(pn.getPn_ngaylap());
                
                model.addRow(row);
        }
        //add model to jtable
        tablephieunhap.setModel(model);
        
        } catch(Exception e)
        {
            System.out.println(e);
            System.out.println("Lỗi đọc phiếu nhập");
        }
    }
    public String format(String a)
    {
        return "Thành công";
    }
    public void docChitiet()
    {
        int j = tablephieunhap.getSelectedRow();
        chitietphieunhapBUS bus = new chitietphieunhapBUS();
//        chitietphieunhapDTO dto = new chitietphieunhapDTO();
        bus.docChitiet1(String.valueOf(tablephieunhap.getValueAt(j, 0)));
        
            int rowCount = modelTb2.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) {
                modelTb2.removeRow(i);
            }
            Vector header = new Vector();
        header.add("Id phiếu nhập");
        header.add("Id SP");
        header.add("Số lượng");
        
        if (modelTb2.getRowCount()==0)
            { 
                modelTb2=new DefaultTableModel(header,0);
            } 
        for(chitietphieunhapDTO ct : chitietphieunhapBUS.dschitiet)
        {
            Vector row = new Vector();
                row.add(ct.getPn_id());
                row.add(ct.getSp_id());
                row.add(ct.getCt_soluong());
                modelTb2.addRow(row);
        }
        tableChitiet.setModel(modelTb2);
    }
    
    
    
    public void hienthi()
    {
        JFrame j = new JFrame();
        j.setSize(1000,700);
        j.setLayout(null);
        JPanel p =new QuanLyPhieuNhap();
        p.setBounds(0, 0, 950, 410);
        
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }
    
    
    private void tablephieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablephieunhapMouseClicked
        // TODO add your handling code here:
        docChitiet();

    }//GEN-LAST:event_tablephieunhapMouseClicked

    private void ChitietBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitietBtnMouseClicked
        // TODO add your handling code here:
        OverrallFrame.changeMainInfo(10);
    }//GEN-LAST:event_ChitietBtnMouseClicked

    private void ChitietBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitietBtnMouseEntered
        // TODO add your handling code here:
        ChitietBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-back-arrow-30.png");
        ChitietBtn.setIcon(logo);
        ChitietBtn.setBackground(Color.blue);
    }//GEN-LAST:event_ChitietBtnMouseEntered

    private void ChitietBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChitietBtnMouseExited
        // TODO add your handling code here:
        ChitietBtn.getDisabledIcon();
        ImageIcon logo = new ImageIcon("./src/img/icons8-back-arrow-30.png");
        ChitietBtn.setIcon(logo);
        ChitietBtn.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_ChitietBtnMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        JFileChooser chooser = new JFileChooser();
//        int i = chooser.showSaveDialog(chooser);
//        if (i == JFileChooser.APPROVE_OPTION) {
//            File file = chooser.getSelectedFile();
//            try {
//                System.out.println(file);
//                Writer bwrite = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8));
//                DefaultTableModel model = (DefaultTableModel) tableChitiet.getModel();
//                // ten Cot
//                for (int j = 0; j < tableChitiet.getColumnCount(); j++) {
//                    bwrite.write(model.getColumnName(j) + "\t");
//                }
//                bwrite.write("\n");
//                // Lay du lieu dong
//                for (int j = 0; j < tableChitiet.getRowCount(); j++) {
//                    for (int k = 0; k < tableChitiet.getColumnCount(); k++) {
//                        bwrite.write(model.getValueAt(j, k) + "\t");
//                    }
//                    bwrite.write("\n");
//                }
//                bwrite.close();
//                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
//            } catch (Exception e2) {
//                System.out.println(e2);
//                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String[] args) 
    {
        JFrame j = new JFrame();
        j.setSize(960,700);
        j.setLayout(null);
        JPanel p =new QuanLyPhieuNhap();
        p.setBounds(0, 0, 960, 700);
        //j.add(g);
        //j.pack();
        j.add(p);
        j.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChitietBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTable tableChitiet;
    private javax.swing.JTable tablephieunhap;
    // End of variables declaration//GEN-END:variables


    }
