/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.DiadiemBLL;
import DTO.DiadiemDTO;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANG MINH HUY
 */
public class DiadiemGUI extends javax.swing.JPanel {
    FormatTable format = new FormatTable();
    /**
     * Creates new form DiadiemGUI
     */
    public static int id;
    public DiadiemGUI() {
        initComponents();
        format.formatTablenoIcon(table);
        loadDstour(new DiadiemBLL().docdsdd());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        them = new javax.swing.JMenuItem();
        sua = new javax.swing.JMenuItem();
        xoa = new javax.swing.JMenuItem();
        reload = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        timkiemtxt = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        popupmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupmenuMouseClicked(evt);
            }
        });

        them.setText("Thêm mới");
        them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themMouseClicked(evt);
            }
        });
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });
        popupmenu.add(them);

        sua.setText("Sửa");
        sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suaMouseClicked(evt);
            }
        });
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });
        popupmenu.add(sua);

        xoa.setText("Xóa");
        xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaMouseClicked(evt);
            }
        });
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        popupmenu.add(xoa);

        reload.setText("reload");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        popupmenu.add(reload);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 0, new java.awt.Color(0, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(

        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 760, 410));

        timkiemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemtxtActionPerformed(evt);
            }
        });
        jPanel1.add(timkiemtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 210, 40));

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-find-and-replace-20.png"))); // NOI18N
        btn.setText("Tìm");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 90, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("QUẢN LÝ ĐỊA ĐIỂM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void timkiemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemtxtActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        loadDstour(new DiadiemBLL().timkiem(timkiemtxt.getText()));
    }//GEN-LAST:event_btnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        //popupmenu.show(this.rootPane,evt.getX(),evt.getY());
    }//GEN-LAST:event_tableMouseClicked

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            popupmenu.show(table,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_tableMouseReleased

    private void themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_themMouseClicked

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        new DiadiemAddDialog().setVisible(true);
    }//GEN-LAST:event_themActionPerformed

    private void suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suaMouseClicked

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
         if(table.getSelectedRow() > -1){
               new DiadiemEditDialog().setVisible(true);
         }else{
             JOptionPane.showMessageDialog(null,"Chọn địa điểm cần xóa");
         }
      
    }//GEN-LAST:event_suaActionPerformed

    private void xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_xoaMouseClicked

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRow() > -1){
            String kq;
            if((kq = new DiadiemBLL().xoa(Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString()))).equals("Xóa thành công")){
                DefaultTableModel  model = (DefaultTableModel)table.getModel();
                model.removeRow(table.getSelectedRow());
            }
            JOptionPane.showMessageDialog(null,kq);
        }else{
            JOptionPane.showMessageDialog(null,"Chọn địa điểm cần xóa");
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        // TODO add your handling code here:
        loadDstour(new DiadiemBLL().docdsdd());
    }//GEN-LAST:event_reloadActionPerformed

    private void popupmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupmenuMouseClicked
        // TODO add your handling code here:
        //popupmenu.show(this.table,evt.getX(),evt.getY());
    }//GEN-LAST:event_popupmenuMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
         if(evt.isPopupTrigger()){
            popupmenu.show(table,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

     private void loadDstour(ArrayList<DiadiemDTO> list){
        String[] header = {"#","Tên thành phố","Tên địa điểm","Mô tả"};
        DefaultTableModel model = new DefaultTableModel(header,0){
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        table.setSelectionMode(SINGLE_SELECTION);
        table.setModel(model);
        table.getColumnModel().getColumn(0).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(1).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(2).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(3).setCellRenderer(new AutoResizeRender());
        for(DiadiemDTO dd : list){
            Object [] data = {dd.getDd_id(),dd.getDd_tp(),dd.getDd_ten(),dd.getMota()};
            model.addRow(data);
        }
        table.getColumnModel().getColumn(0).setPreferredWidth(1);
        table.getColumnModel().getColumn(1).setPreferredWidth(70);
        table.getColumnModel().getColumn(2).setPreferredWidth(150);
        table.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JMenuItem reload;
    private javax.swing.JMenuItem sua;
    public static javax.swing.JTable table;
    private javax.swing.JMenuItem them;
    private javax.swing.JTextField timkiemtxt;
    private javax.swing.JMenuItem xoa;
    // End of variables declaration//GEN-END:variables
}
