
package GUI;

import BLL.DiadiemBLL;
import DTO.DiadiemDTO;
import static GUI.DiadiemGUI.id;
import static GUI.DiadiemGUI.table;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DiadiemAddDialog extends javax.swing.JFrame {

    /**
     * Creates new form DiadiemEditDialog
     */
    int id;
    public DiadiemAddDialog() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mttxt = new javax.swing.JTextArea();
        tptxt = new javax.swing.JTextField();
        ddtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mttxt.setColumns(10);
        mttxt.setRows(5);
        jScrollPane1.setViewportView(mttxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 123, 170, -1));
        getContentPane().add(tptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 27, 166, 30));
        tptxt.getAccessibleContext().setAccessibleDescription("");

        ddtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddtxtActionPerformed(evt);
            }
        });
        getContentPane().add(ddtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 166, 31));

        jButton1.setText("Xác nhận");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Mô tả:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel13.setText("Tên địa điểm:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel14.setText("Thành phố:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddtxtActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String tb = "";
        if(ddtxt.getText().equals("")){
            tb+="Tên địa điểm không được để trống\n";
        }
        if(tptxt.getText().equals("")){
            tb+="Tên thành phố không được để trống\n";
        }
        if(mttxt.getText().equals("")){
            tb+="Mô tả không được để trống\n";
        }
        if(!tb.equals("")){
             JOptionPane.showMessageDialog(null,tb);
        }else{
            DiadiemBLL bll = new DiadiemBLL();
            DiadiemDTO dd = new DiadiemDTO(table.getRowCount()+1,tptxt.getText().toString(),ddtxt.getText().toString(),mttxt.getText().toString());
            if(bll.them(dd)){
                JOptionPane.showMessageDialog(null,"Thành công");
                Object [] newrow = {Integer.parseInt(table.getValueAt(table.getRowCount()-1,0).toString())+1,tptxt.getText().toString(),ddtxt.getText().toString(),mttxt.getText().toString()};
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(newrow);
                table.setModel(model);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Thất bại");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiadiemAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiadiemAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiadiemAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiadiemAddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiadiemAddDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField ddtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea mttxt;
    private static javax.swing.JTextField tptxt;
    // End of variables declaration//GEN-END:variables
}
