/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.NhanVienBLL;
import DTO.NhanvienDTO;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nam
 */
public class EmployeeMainPanel extends javax.swing.JPanel {
    FormatTable formatTable = new FormatTable();
    NhanVienBLL bus = new NhanVienBLL();
    DefaultTableModel model =new DefaultTableModel();
    CheckLoi cl = new CheckLoi();

    /**
     * Creates new form EmployeePanel
     */
    public EmployeeMainPanel() {
        initComponents();
        init();
    }
    
    public void init()
    {
        formatTable.formatTablenoIcon(table);
        
        //Header content of jtable
        bus.docNhanvien();
        Vector header = new Vector();
        header.add("ID");
        header.add("Tên");
        header.add("Điện thoại");
        header.add("Ngày sinh");
        header.add("Email");
        header.add("Nhiệm vụ");
        header.add("Tình Trạng");
        header.add("");
        header.add("");
        if (model.getRowCount()==0)
        { 
                model=new DefaultTableModel(header,0){
                @Override//No edit
                public boolean isCellEditable(int row, int column) 
                {       
                    if(column == 7 || column == 8)
                    {
                        return true;
                    } else {
                        return false;
                    }
                }
            };
        } 
        table.setModel(model);
        docNhanvien();
        
        //format table
        table.getColumnModel().getColumn(7).setCellEditor(new EditButtonEmployRender(table));
        table.getColumnModel().getColumn(7).setCellRenderer(new EditButtonEmployRender(table));
        table.getColumnModel().getColumn(8).setCellEditor(new RemoveButtonEmployRender(table));
        table.getColumnModel().getColumn(8).setCellRenderer(new RemoveButtonEmployRender(table));
        
        table.getColumnModel().getColumn(0).setPreferredWidth(5);
        table.getColumnModel().getColumn(2).setPreferredWidth(45);
        table.getColumnModel().getColumn(3).setPreferredWidth(45);
        table.getColumnModel().getColumn(7).setPreferredWidth(20);
        table.getColumnModel().getColumn(8).setPreferredWidth(20);

    }
    
    
    
    public void refresh()
    {
        init();
        searchTxt.setText("");
    }
    
    public void docNhanvien()
    {
        try
        {
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
            for(NhanvienDTO nv : NhanVienBLL.sumArr)
            {
                Vector row = new Vector();
                row.add(nv.getNv_id());
                row.add(nv.getNv_ten());
                row.add(nv.getNv_sdt());
                row.add(nv.getNv_ngaysinh());
                row.add(nv.getNv_email());                
                row.add(nv.getNv_nhiemvu());                               
                row.add(nv.formatTrangthai());
                
                model.addRow(row);
            }
            table.setModel(model);
        
        } catch(Exception e) {
            System.out.println("Lỗi đọc nhân viên GUI");
        }
    }
    
    public void search()
    {
        int rowCount = model.getRowCount();//remove all row
        for (int i = rowCount - 1; i >= 0; i--) 
        {
            model.removeRow(i);
        }
        for(NhanvienDTO nv : bus.search(searchTxt.getText().toUpperCase(), combobox.getSelectedIndex()))
        {
            Vector row = new Vector();
            row.add(nv.getNv_id());
            row.add(nv.getNv_ten());
            row.add(nv.getNv_sdt());
            row.add(nv.getNv_ngaysinh());
            row.add(nv.getNv_email());
            row.add(nv.getNv_nhiemvu());
            row.add(nv.formatTrangthai());

            model.addRow(row);
        }
        table.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 0, new java.awt.Color(51, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setFillsViewportHeight(true);
        table.setName(""); // NOI18N
        table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 740, 330));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-user-menu-male-30.png"))); // NOI18N
        jLabel1.setText(" DANH SÁCH NHÂN VIÊN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 780, 410));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 51, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-add-20.png"))); // NOI18N
        addBtn.setText("Thêm mới nhân viên");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        refreshBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-update-left-rotation-20.png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel2.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        combobox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tên", "Số điện thoại", "Nhiệm vụ", "Email" }));
        jPanel2.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));
        jPanel2.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-find-and-replace-20.png"))); // NOI18N
        searchBtn.setText("Tìm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 80, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, 100));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("QUẢN LÝ NHÂN VIÊN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        OverrallFrame.changeMainInfo(8);
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
