/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.DoanBLL;
import static BLL.DoanBLL.sumArrDoan;
import DTO.DoanDTO;
import static GUI.EditDoanPanel.currentIddoan;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nam
 */
public class QLDoanMainPanel extends javax.swing.JPanel {
    FormatTable formatTable = new FormatTable();
    DoanBLL bus = new DoanBLL();
    DefaultTableModel model =new DefaultTableModel();
    /**
     * Creates new form EmployeePanel
     */
    public QLDoanMainPanel() {
        initComponents();
        init();
    }
    
    
    public void init()
    {
        formatTable.formatTablenoIcon(table);
        
        //Header content of jtable
        bus.docDoan();
        Vector header = new Vector();
        header.add("ID");
        header.add("Tên");
        header.add("Ngày đi");
        header.add("Ngày về");
        header.add("Mô tả");
        header.add("Tình trạng");
        header.add("");
        if (model.getRowCount()==0)
        { 
                model=new DefaultTableModel(header,0){
                @Override//No edit
                public boolean isCellEditable(int row, int column) 
                {          
                    if(column == 6)
                    {
                        return true;
                    } else {
                        return false;
                    }
                }
            };
        } 
        
        table.setModel(model);
        docDoan();
        
        //format table
        table.getColumnModel().getColumn(6).setCellEditor(new RemoveButtonDoanRender(table));
        table.getColumnModel().getColumn(6).setCellRenderer(new RemoveButtonDoanRender(table));
        
        table.getColumnModel().getColumn(0).setPreferredWidth(5);
        table.getColumnModel().getColumn(1).setPreferredWidth(130);
        table.getColumnModel().getColumn(2).setPreferredWidth(43);
        table.getColumnModel().getColumn(3).setPreferredWidth(43);
        table.getColumnModel().getColumn(4).setPreferredWidth(150);
        table.getColumnModel().getColumn(6).setPreferredWidth(15);

        
    }
    
    public void refresh()
    {
        init();
        searchTxt.setText("");
    }
    
    public void docDoan()
    {
        try
        {
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
            for(DoanDTO nv : DoanBLL.sumArrDoan)
            {
                Vector row = new Vector();
                row.add(nv.getDoan_id());
                row.add(nv.getDoan_ten());
                row.add(nv.getDoan_ngaydi());
                row.add(nv.getDoan_ngayve());
                row.add(nv.getDoan_chitiet());                
                row.add(nv.formatTinhtrang());                
                
                model.addRow(row);
            }
            table.setModel(model);
        
        } catch(Exception e) {
            System.out.println("Lỗi đọc đoàn GUI");
        }
    }
    
    public void search()
    {
        int rowCount = model.getRowCount();//remove all row
        for (int i = rowCount - 1; i >= 0; i--) 
        {
            model.removeRow(i);
        }
        for(DoanDTO nv : bus.search(searchTxt.getText().toUpperCase(), combobox.getSelectedIndex()))
        {
            Vector row = new Vector();
            row.add(nv.getDoan_id());
            row.add(nv.getDoan_ten());
            row.add(nv.getDoan_ngaydi());
            row.add(nv.getDoan_ngayve());
            row.add(nv.getDoan_chitiet());
            row.add(nv.formatTinhtrang());

            model.addRow(row);
        }
        table.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        nhapchiphiBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 0, new java.awt.Color(51, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setFillsViewportHeight(true);
        table.setName(""); // NOI18N
        table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 740, 330));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-user-menu-male-30.png"))); // NOI18N
        jLabel1.setText(" DANH SÁCH ĐOÀN ĐI TOUR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 780, 410));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 0, new java.awt.Color(0, 51, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-add-20.png"))); // NOI18N
        addBtn.setText("Lập đoàn đi tour");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 30));

        refreshBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-update-left-rotation-20.png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel2.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        editBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-edit-20.png"))); // NOI18N
        editBtn.setText("Sửa thông tin");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel2.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 140, 30));

        combobox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tên", "Ngày đi", "Ngày về", "Chi tiết" }));
        jPanel2.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));
        jPanel2.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 30));

        searchBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-find-and-replace-20.png"))); // NOI18N
        searchBtn.setText("Tìm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 80, 30));

        nhapchiphiBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nhapchiphiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-money-transfer-20.png"))); // NOI18N
        nhapchiphiBtn.setText("Nhập chi phí");
        nhapchiphiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapchiphiBtnActionPerformed(evt);
            }
        });
        jPanel2.add(nhapchiphiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 140, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-hand-with-pen-20.png"))); // NOI18N
        jButton4.setText("Sửa chi phí ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 150, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, 100));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("QUẢN LÝ ĐOÀN ĐI TOUR ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void nhapchiphiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapchiphiBtnActionPerformed
        // TODO add your handling code here:
        int i = table.getSelectedRow();
        if(table.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn đoàn cần nhập chi phí");
        } else if(table.getValueAt(i, 5).toString().equals("Đã nhập chi phí"))
        {
            JOptionPane.showMessageDialog(null, "Đoàn này đã nhập chi phí. Hãy chọn sửa chi phí");
        } else {
            AddChiphiDoanPanel.currentDoan_id = Integer.parseInt(table.getValueAt(i, 0).toString());
            AddChiphiDoanPanel.currentDoan_ten = table.getValueAt(i, 1).toString();
            OverrallFrame.changeMainInfo(14);
        }
    }//GEN-LAST:event_nhapchiphiBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        OverrallFrame.changeMainInfo(12);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        if(table.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn đoàn cần sửa thông tin");
        } else {
            int i = table.getSelectedRow();
            EditDoanPanel.currentIddoan = Integer.parseInt(table.getValueAt(i, 0).toString());
            OverrallFrame.changeMainInfo(13);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int i = table.getSelectedRow();

        if(table.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "Chưa chọn đoàn cần sửa chi phí");
        } else if(table.getValueAt(i, 5).toString().equals("Chưa nhập chi phí"))
        {
            JOptionPane.showMessageDialog(null, "Đoàn này chưa nhập bất kì chi phí nào");
        } else {
            EditChiphiDoanPanel.currentDoan_id = Integer.parseInt(table.getValueAt(i, 0).toString());
            EditChiphiDoanPanel.currentDoan_ten = table.getValueAt(i, 1).toString();
            OverrallFrame.changeMainInfo(15);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox combobox;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nhapchiphiBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
