/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.ChitietTourBLL;
import BLL.DiadiemBLL;
import BLL.LoaiTourBLL;
import BLL.TourBLL;
import DTO.ChitietTourDTO;
import DTO.TourDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static GUI.TourGUI.table;
import javax.swing.table.DefaultTableModel;
import static GUI.ThemGiaGUI.row;

public class ThemTourGUI extends javax.swing.JFrame {

    /**
     * Creates new form ThemDiadiemDTO
     */
    ArrayList<String>temp = new ArrayList();
    String temp2 = "";
    DefaultListModel<String> model = new DefaultListModel<>();
    public static int id2=1;
    public ThemTourGUI() {
        initComponents();
        loadCombobox2();
        loadCombobox1();
        loadList();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        comboboxloai = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        tentxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        motatxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        comboboxtp = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JButton();
        removebtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 136, 160));

        comboboxloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboboxloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxloaiActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 230, 40));

        list2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 130, 160));

        tentxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentxtActionPerformed(evt);
            }
        });
        getContentPane().add(tentxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 230, 40));

        motatxt.setLineWrap(true);
        motatxt.setColumns(20);
        motatxt.setRows(5);
        jScrollPane3.setViewportView(motatxt);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 230, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-save-all-20.png"))); // NOI18N
        jButton1.setText("Lưu thông tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 190, 40));

        comboboxtp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxtpActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 147, 29));

        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/add.png"))); // NOI18N
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 55, 45));

        removebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/remove.png"))); // NOI18N
        removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtnActionPerformed(evt);
            }
        });
        getContentPane().add(removebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 54, 45));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Tên tour:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel14.setText("Mô tả:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel15.setText("Loại tour:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Chi tiết tour:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 170, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel16.setText("Chọn thành phố:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TẠO TOUR MỚI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadCombobox1(){
        DefaultComboBoxModel loaicbModel = new DefaultComboBoxModel(new LoaiTourBLL().dsloai().toArray());
        comboboxloai.setModel(loaicbModel);
    }
    private void loadCombobox2(){
        DefaultComboBoxModel loaicbModel = new DefaultComboBoxModel(new DiadiemBLL().docdstp().toArray());
        comboboxtp.setModel(loaicbModel);
    }
    
    private void loadList(){
        DefaultListModel<String> model = new DefaultListModel<>();
        for(String s : new DiadiemBLL().docDsdd(comboboxtp.getSelectedItem().toString())){
            model.addElement(s);
        }
        list1.setModel(model);
    }
    
    private String loadDd(){
        String kq="";
        for(String s : temp){
            kq+=s+"-";
        }
        return kq.substring(0,kq.length()-1);
    }
    
    private void comboboxloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxloaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxloaiActionPerformed

    private void tentxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tentxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tb="";
        if(temp.size()==0){
            tb+="Danh sách địa điểm không được để trống\n";
        }
        if(tentxt.getText().equals("")){
            tb+="Tên tour không được để trống\n";
        }
        if(motatxt.getText().equals("")){
            tb+="Tên thành phố không được để trống\n";
        }
        if(new TourBLL().checkTen(tentxt.getText().toString())){
            tb+="Tên tour trùng\n";
        }
        if(!tb.equals("")){
             JOptionPane.showMessageDialog(null,tb);
        }else{
            boolean check = true;
            try{
                id2=Integer.parseInt(table.getValueAt(table.getRowCount()-1,0).toString())+1;
            }catch(Exception e){
                
            }
            if(!new TourBLL().them(new TourDTO(id2,tentxt.getText().toString(),
                    motatxt.getText().toString(),comboboxloai.getSelectedIndex()+1)))
                    check = false;
            else{
                int count=1;
                for(String s : temp){
                    if(!new ChitietTourBLL().them(new ChitietTourDTO(new ChitietTourBLL().docdsdetail().size()+1,
                            id2,count++,new DiadiemBLL().getId(s))))
                        check = false;
                }
            }
            if(check == true){
                JOptionPane.showMessageDialog(null,"Vui long them gia");
                Object [] newrow = {id2,tentxt.getText().toString(),motatxt.getText().toString(),
                     comboboxloai.getSelectedItem(),loadDd()};
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(newrow);
                table.setModel(model);
                new ThemGiaGUI().setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Thất bại");
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboboxtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxtpActionPerformed
        // TODO add your handling code here:
        loadList();
    }//GEN-LAST:event_comboboxtpActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        if(list1.getSelectedValue()== null){
            JOptionPane.showMessageDialog(null,"Chưa chọn địa điểm");
        }else{
            list2.setModel(model);
            if(temp2.equals(list1.getSelectedValue()))
               JOptionPane.showMessageDialog(null,"Địa điểm vừa chọn trước đó"); 
            else{
                temp.add(temp2=list1.getSelectedValue());
                model.addElement(list1.getSelectedValue());
            }
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void removebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebtnActionPerformed
        // TODO add your handling code here:
        if(list2.getSelectedValue() == null){
            JOptionPane.showMessageDialog(null,"Chưa chọn địa điểm");
        }else{
            temp.remove(list2.getSelectedValue());
            model.removeElementAt(list2.getSelectedIndex());
        }
    }//GEN-LAST:event_removebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemTourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemTourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemTourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemTourGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemTourGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JComboBox<String> comboboxloai;
    private javax.swing.JComboBox<String> comboboxtp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JTextArea motatxt;
    private javax.swing.JButton removebtn;
    private javax.swing.JTextField tentxt;
    // End of variables declaration//GEN-END:variables
}
