/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ChitietTourBLL;
import BLL.DiadiemBLL;
import BLL.LoaiTourBLL;
import BLL.TourBLL;
import DTO.TourDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.table.DefaultTableModel;
import static GUI.ThemGiaGUI.row;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author HOANG MINH HUY
 */
public class TourGUI extends javax.swing.JPanel {
    FormatTable format = new FormatTable();
    /**
     * Creates new form TourGUI
     */
    public TourGUI() {
        initComponents();
        format.formatTablenoIcon(table);
        loadDstour(new TourBLL().docdsdd());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        them = new javax.swing.JMenuItem();
        sua = new javax.swing.JMenuItem();
        xoa = new javax.swing.JMenuItem();
        xem = new javax.swing.JMenuItem();
        reload = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        timkiemtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });
        popupmenu.add(them);

        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });
        popupmenu.add(sua);

        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        popupmenu.add(xoa);

        xem.setText("Xem giá");
        xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemActionPerformed(evt);
            }
        });
        popupmenu.add(xem);

        reload.setText("reload");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        popupmenu.add(reload);

        setBackground(new java.awt.Color(204, 204, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 0, 0, new java.awt.Color(0, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 760, 420));

        timkiemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemtxtActionPerformed(evt);
            }
        });
        jPanel1.add(timkiemtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 240, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8-find-and-replace-20.png"))); // NOI18N
        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 100, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("QUẢN LÝ TOUR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadDstour(new TourBLL().timkiem(timkiemtxt.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMousePressed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            popupmenu.show(this,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_tableMouseReleased

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        new ThemTourGUI().setVisible(true);
    }//GEN-LAST:event_themActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null,"Chọn tour cần sửa");
        }else{
            new SuaTourGUI().setVisible(true);
        }
    }//GEN-LAST:event_suaActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null,"Chọn tour cần xóa");
        }else{
            if(new TourBLL().xoa(new SimpleDateFormat("yyyy-MM-dd").format(new Date()),Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString()))){
                DefaultTableModel  model = (DefaultTableModel)table.getModel();
                model.removeRow(table.getSelectedRow());
                JOptionPane.showMessageDialog(null,"Thành công");
            }else{
                JOptionPane.showMessageDialog(null,"Thất bại!! Còn đoàn đi!!");
            }
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemActionPerformed
        // TODO add your handling code here:
        if(table.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null,"Chọn tour cần xem");
        }else{
            row = table.getSelectedRow();
            new GiaGUI().setVisible(true);
        }
    }//GEN-LAST:event_xemActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        // TODO add your handling code here:
        loadDstour(new TourBLL().docdsdd());
    }//GEN-LAST:event_reloadActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            popupmenu.show(this,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void timkiemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemtxtActionPerformed

  public void loadDstour(ArrayList<TourDTO> list){
        String[] header = {"#","Tên tour","Mô tả","Loại tour","Danh sách các điểm đếm"};
        DefaultTableModel model = new DefaultTableModel(header,0){
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        table.setSelectionMode(SINGLE_SELECTION);
        table.setModel(model);
        table.getColumnModel().getColumn(0).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(1).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(2).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(3).setCellRenderer(new AutoResizeRender());
        table.getColumnModel().getColumn(4).setCellRenderer(new AutoResizeRender());
        for(TourDTO tour : list){
            Object [] data = {tour.getTour_id(),tour.getTour_ten(),tour.getTour_mota(),new LoaiTourBLL().getTenloai(tour.getLoai_id()),
            new ChitietTourBLL().docdd(tour.getTour_id())};
            model.addRow(data);
        }
        table.getColumnModel().getColumn(0).setPreferredWidth(1);
        table.getColumnModel().getColumn(1).setPreferredWidth(50);
        table.getColumnModel().getColumn(2).setPreferredWidth(100);
        table.getColumnModel().getColumn(3).setPreferredWidth(150);
        table.getColumnModel().getColumn(4).setPreferredWidth(300);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JMenuItem reload;
    private javax.swing.JMenuItem sua;
    public static javax.swing.JTable table;
    private javax.swing.JMenuItem them;
    private javax.swing.JTextField timkiemtxt;
    private javax.swing.JMenuItem xem;
    private javax.swing.JMenuItem xoa;
    // End of variables declaration//GEN-END:variables
}
